add HTML for header
OpenEugene/eugene-food-scene pull request #9
Opened 2020-06-30 23:36 UTC by ArthurSmid

This is the header image as HTML and CSS.

2020-06-30 23:57 UTC, markdav-is requested changes

2020-06-30 23:57 UTC, nohorse commented on EugeneFoodScene/Client/Shared/Header.razor
> +<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">
these belong in index.html in wwwroot

2020-06-30 23:57 UTC, nohorse commented on EugeneFoodScene/Client/Shared/Header.razor
> +    <h2 class="support">Support Local Restaurants</h2>
add a clls for the h123-reset

2020-06-30 23:57 UTC, nohorse commented on EugeneFoodScene/Client/Shared/Header.razor
> +    <h2 class="support">Support Local Restaurants</h2>
add class is what I meant

2020-06-30 23:59 UTC, ArthurSmid reviewed
removed the Google Font links

2020-07-01 00:02 UTC, markdav-is approved these changes

2020-07-01 00:02 UTC, merged